export { default as Instagram } from './instagram.svg'
export { default as Facebook } from './facebook.svg'
export { default as LinkedIn } from './linkedin.svg'
export { default as Menu } from './menu.svg'
export { default as Arrow } from './right-arrow.svg'
export { default as Envelop } from './mail.svg'
export { default as Send } from './send.svg'
export { default as WhatsApp } from './whatsapp.svg'
export { default as Github } from './github.svg'
export { default as Twitter } from './twitter.svg'
export { default as Mouse } from './mouse3-fill.svg'

